project: 
  type: manuscript

manuscript:
  article: manuscript.qmd
  meca-bundle: "bundle.zip"
  code-links: [binder, repo]
  notebooks:
    - notebook: analysis/primary_analyses.qmd
      title: "1. Primary Analyses"
    - notebook: analysis/secondary_analyses.qmd
      title: "2. Secondary Analyses"
    - notebook: analysis/bonus_materials.qmd
      title: "3. Bonus Materials"
  resources:
    - data/
    - materials/
    - results/

format:
  html:
    toc: true
    comments:
      hypothesis: false
    theme: [brand, styles.scss]
    grid:
      body-width: 900px
  jats: default
  # apaquarto-pdf:
  #   documentmode: man
  #   a4paper: true
  #   keep-tex: true
  apaquarto-typst:
    documentmode: man
    a4paper: true
  apaquarto-docx:
    a4paper: true

notebook-links: global

execute:
  freeze: false
  echo: false
