project: 
  type: manuscript

manuscript:
  article: manuscript.qmd
  meca-bundle: "reproduction_bundle.zip"
  code-links: [binder, repo]
  notebooks:
    - notebook: analysis/primary_analyses.qmd
      title: "1. Primary Analyses"
    - notebook: analysis/secondary_analyses.qmd
      title: "2. Secondary Analyses"
    - notebook: analysis/bonus_materials.qmd
      title: "3. Bonus Materials"
  resources:
    - data/
    - materials/
    - results/

format:
  apaquarto-html:
  #  theme: default
    suppress-title-introduction: true
    suppress-title: false
    toc: true
    toc-depth: 3
    comments:
      hypothesis: false
    citation:
      type: article-journal
      container-title: "PsyArxiv"
      id: "eichhorn2025"
      issued: 2025
  #  theme: [brand, styles.scss]
    grid:
      body-width: 900px
  jats: default
  # apaquarto-pdf:
  #   documentmode: man
  #   a4paper: true
  #   keep-tex: true
  apaquarto-typst:
    documentmode: man
    a4paper: true
  apaquarto-docx:
    documentmode: man
    a4paper: true
    
format-links:
  - apaquarto-html
  - format: apaquarto-typst
    text: PDF
  - format: apaquarto-docx
    text: MS Word

notebook-links: global

execute:
  freeze: false
  echo: false
