---
title: "Manuscript"
date: today
date-modified: today
date-format: iso
author:
  - name: Kathryn Eichhorn
    equal-contributor: true
    orcid: 0000-0003-3676-9420
    role: 
      - conceptualization
      - investigation
      - resources
      - data curation
      - writing
    affiliations:
      - name: University of the Bundeswehr Munich
        department: Institute of Psychology
        city: Neubiberg
        country: Germany
  - name: Markus Bühner
    corresponding: true
    equal-contributor: true
    email: buehner@lmu.de
    orcid: 0000-0002-0597-8708
    role: 
      - formal analysis
      - supervision
      - writing
    affiliations:
      - id: "lmu"
        name: LMU Munich
        department: Department of Psychology
        address: Leopoldstr. 13
        city: D-80802 Munich
        country: Germany
        postal-code: 80802
  - name: Florian Pargent
    orcid: 0000-0002-2388-553X
    role:
      - formal analysis
      - software
      - validation
      - editing
    affiliations:
      - ref: lmu
  - name: Janika Saretzki
    orcid: ~
    role:
      - editing
    affiliations:
      - name: University of Graz
        department: Department of Psychology
        city: Graz
        country: Austria
      - name: Charlotte Fresenius University of Psychology
        city: Munich
        country: Germany
      - ref: lmu
  - name: Larissa Sust
    orcid: 0000-0002-3389-1626
    role:
      - editing
    affiliations:
      - ref: lmu
  - name: Jonas Hauck
    orcid: ~
    role:
      - editing
    affiliations:
      - id: "regen"
        name: University of Regensburg
        department: Faculty of Psychology
        city: Regensburg
        country: Germany
  - name: Sven Hilbert
    orcid: ~
    role:
      - conceptualization
      - supervision
      - editing
    affiliations:
      - ref: regen
    
author-note:
  disclosures:
    data-sharing: This is version 1 of our preprint published at <LINK>. All materials (reproducible manuscript, analysis code, data) are available in the project's repository on the Open Science Framework (OSF) at <LINK>. A Quarto Manuscripts website is hosted at <LINK>.
    conflict-of-interest: The authors declare that there were no conflicts of interest concerning the authorship or the publication of this article.
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
language:
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; <https://credit.niso.org/>):"
abstract: Abstract Text
keywords: [keyword1, keyword2]
license: CC BY 4.0
bibliography: [references.bib]
floatsintext: true
numbered-lines: false
csl: apa.csl
---

```{r}
#| label: setup
#| include: false
library(foreign)
library(flextable)
dat_poly <- read.spss("data/Haupterhebung Studie III (Polytom 6PS).sav", 
  to.data.frame = TRUE, use.value.labels = FALSE, na.omit = FALSE)
dat_dich <- read.spss("data/Haupterhebung Studie III (Dichotom 2PS).sav",
  to.data.frame = TRUE, use.value.labels = FALSE, na.omit = FALSE)

results <- readRDS("results/results.rds")
results_secondary <- readRDS("results/results_secondary.rds")
```

# Introduction

# Methods

```{r}
#| label: "tbl-1"
#| tbl-cap: Descriptive statistics of demographic variables for 6 and 2 response categories
#| ft.align: left
#| disable-apaquarto-processing: false

results$table1
```


# Results


```{r}
#| label: "tbl-2"
#| tbl-cap: Standardized item loadings (correlations with the latent variable) for 6 and 2 response categories 
#| ft.align: left
#| disable-apaquarto-processing: false
#| apa-note: CFI = Comparative Fit Index (scaled). RMSEA = Root Mean Squared Error of Approximation (scaled). SRMR = Standardized Root Mean Residual. Scaled chi-square, scaled df, and scaled p-value are reported. Correlations with the latent variable higher as the self-reported physical item are printed in bold typeface.

results$table2
```
::: {.content-visible when-format="html"}
*Note.* Add table note for html format here.
:::

As we can see in @tbl-2 ...

```{r}
#| label: "tbl-3"
#| tbl-cap: Standardized item loadings on the general latent variable for 6 categories controlling for the self-reported physical item and self-reported sex.
#| ft.align: left
#| disable-apaquarto-processing: false
#| apa-note: Loadings on the latent variable or standardized regression weights of the self-reported physical item and self-reported sex greater than .60 are printed in bold typeface.

results$table3
```
::: {.content-visible when-format="html"}
*Note.* Add table note for html format here.
:::

As we can see in @tbl-3 ...

```{r}
#| label: "tbl-4"
#| tbl-cap: Latent correlations between the latent variables age, body height and body weight for 6 and 2 categories
#| ft.align: left
#| apa-note: Above the diagonal the correlations between the latent variables are shown and below the diag-onal the correlations between the self-reported physical measures are shown. The latent correla-tions were taken out of latent variable models (6 and response categories) including all self-reported physical items and all latent variables with the allocated items. The models showed the following fit. In the diagonal are the reliability estimates Omega for the scales.

results$table4
```
::: {.content-visible when-format="html"}
*Note.* Add table note for html format here.
:::

As we can see in @tbl-4 ...

# Discussion


# References

::: {#refs}
:::

# Appendix

```{r}
#| label: "tbl-5"
#| tbl-cap: Latent variable loadings for 6 and 2 response categories with correlated errors 
#| ft.align: left
#| disable-apaquarto-processing: false
#| apa-note: CFI = Comparative Fit Index (scaled). RMSEA = Root Mean Squared Error of Approximation (scaled). SRMR = Standardized Root Mean Residual. Scaled chi-square, scaled df (degrees of freedom), and scaled p-value are reported. Best Fit indices are printed in bold typeface. Loadings higher than the loading of the self-reported physical item are printed in bold typeface.

results_secondary$table5
```
::: {.content-visible when-format="html"}
*Note.* Add table note for html format here.
:::

```{r}
#| label: "table6"
```
::: {.content-visible when-format="html"}
*Note.* Add table note for html format here.
:::
